### ISSUE TITLE
RelatedParty : retrieve account throw exception if undefined

### ISSUE THREAD

**Issue by sdespont** [genkgo/camt#73] opened 2018-04-12 13:22 UTC
Why `RelatedParty `class throws an exception if we try to retrieve an undefined account? I would like to display the IBAN if it is provided, but if it is not, an exception occurred.

So, how can I know if the account is available?

https://github.com/genkgo/camt/blob/478aa0a0691240c2c76d3b16282da1c80d9c79f0/src/DTO/RelatedParty.php#L40-L49

**Comment by PowerKiKi** [comment] 2019-05-06 03:02
If the related party account does not exist should RelatedParty never be created in the first place ? And thus preventing your case altogether ?

**Comment by PowerKiKi** [comment] 2019-05-06 03:07
Duplicate of #50

**Closed by PowerKiKi** 2019-05-06 03:07 UTC
